#!/usr/bin/env ruby
# frozen_string_literal: true

# Be like rspec
require 'pathname'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile',
                                           Pathname.new(__FILE__).realpath)

require 'rubygems'
require 'bundler/setup'
require 'rspec'
require 'rspec/core/runner'

require 'json'
require 'sonoko'

Sonoko::Config.repo_root = Pathname.new(
  File.join(File.dirname($PROGRAM_NAME), '..')
).realpath

args = ['-f', 'Sonoko::Formatter', *ARGV]
RSpec::Core::Runner.run(args)

puts JSON.pretty_generate(Sonoko::Config.tracer.event_examples)
