#!/usr/bin/env ruby
# frozen_string_literal: true

# Be like rspec
require 'pathname'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile',
                                           Pathname.new(__FILE__).realpath)

require 'rubygems'
require 'bundler/setup'
require 'rspec'
require 'rspec/core/runner'

require 'json'
require 'sonoko'

Sonoko::Formatter.register
Sonoko::Config.tracer.new_db!

args = ['-f', 'Sonoko::Formatter', *ARGV]

RSpec::Core::Runner.run(args)
